#!/usr/bin/bash

# Test if environmental variable UTILS exists
test ! -n "${UTILS}" && echo "UTILS not set" && exit 1

# Test if the command has the name of the new script
test ! -n "${1}" && echo "usage: newx <script name>" && exit 1

script=${1}
path="${UTILS}/${script}"

# if the script already exists, asks for edition
if test -e "${path}"; then
    read -p "${script} already exists. Edit? " yes
    case "${yes}" in
        y|yes|yep|yeah|ok|okay) exec nvim "${path}"
    esac
    exit 0
fi

# Create the file
printf "#!/usr/bin/bash\n\n" > "${path}"

# Make the file executable
chmod +x "${path}"

# Edit with nvim (starting on the second line)
exec nvim +2 "${path}"
