#!/usr/bin/bash

# View status of all repos

for repo in $(ls ${REPOS}); do
    cd "${REPOS}${repo}"
    echo "--------------------"
    echo "${repo}"
    echo "--------------------"
    git status
    printf "\n"
done
