#!/usr/bin/bash
# Back up vimwiki folder

echo "Backing up vimwiki..."
cd "${VIMWIKI}"
git status
git add . && git commit -m "daily backup" && echo "Backed up!!"
sleep 1
echo "Pushing to remote..."
git push
