#!/usr/bin/bash
# Shows titles of my Zettelkasten

for directory in $(ls -d ${ZETTELKASTEN}*/); do
    echo "--------------"
    ztag="${directory%/}"
    ztag="${ztag##*/}"
    title=`cat "${directory}/README.md" | grep "^# "`
    echo "${ztag} --- ${title}"
done
